public class MathematicalClass {
    public integer addition(integer num1, integer num2){
       integer  result = num1 + num2;
        return result;
    }
    public integer subtraction (integer num1, integer num2){
        integer result = num1-num2;
        return result;
    }
    public integer multiplication (integer num1, integer num2){
        integer result= num1*num2;
        return result ;
    }
    public integer division (integer num1, integer num2){
        integer result = num1/num2;
        return result;
    }
}
