public  class Address {
    public void homeAddress(){
        string yourName= 'Elif Yildirim';
        System.debug('My Name is: '+yourName);

        integer totalNumberOfMembersInYourFamily=5;
        System.debug('Family members: '+totalNumberOfMembersInYourFamily);

        string houseName='Marine Towers';
        System.debug('House Name is: '+houseName);

        string houseNumber= '1915';
        System.debug('House number is: '+houseNumber);

        string streetName= 'Shannont St.';
        System.debug('Street name is: '+streetName);

        string cityName= 'Tempe.';
        System.debug('City name is: '+cityName);

        string stateName= 'Arizona';
        System.debug('State name is: '+stateName);

        string stateIsoCode= '1234';
        System.debug('State ISO code is: '+stateIsoCode);

        string countryName= 'Maricopa Country';
        System.debug('Country name is: '+countryName);

        string countryIsoCode= '4567';
        System.debug('Country ISO code is: '+countryIsoCode);

        string zipCode= '6789';
        System.debug('Zip code is: '+zipCode);

        boolean isThisYourCurrentHome= true;
        System.debug('Is this your current home or not: '+isThisYourCurrentHome);




        
         

    }
}
